# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_create_interview.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from vt_connection import vtConnection


class Ui_FormAddNewInterview(object):
    def setupUi(self, FormAddNewInterview):
        FormAddNewInterview.setObjectName("FormAddNewInterview")
        FormAddNewInterview.resize(1039, 841)
        self.tableWidgetListFirms = QtWidgets.QTableWidget(FormAddNewInterview)
        self.tableWidgetListFirms.setGeometry(QtCore.QRect(70, 60, 911, 301))
        self.tableWidgetListFirms.setObjectName("tableWidgetListFirms")
        self.tableWidgetListFirms.setColumnCount(7)
        self.tableWidgetListFirms.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListFirms.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListFirms.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListFirms.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListFirms.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListFirms.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListFirms.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListFirms.setHorizontalHeaderItem(6, item)
        self.tableWidgetListFirms.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidgetListUnemployeds = QtWidgets.QTableWidget(FormAddNewInterview)
        self.tableWidgetListUnemployeds.setGeometry(QtCore.QRect(60, 490, 911, 301))
        self.tableWidgetListUnemployeds.setObjectName("tableWidgetListUnemployeds")
        self.tableWidgetListUnemployeds.setColumnCount(10)
        self.tableWidgetListUnemployeds.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListUnemployeds.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListUnemployeds.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListUnemployeds.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListUnemployeds.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListUnemployeds.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListUnemployeds.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListUnemployeds.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListUnemployeds.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListUnemployeds.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListUnemployeds.setHorizontalHeaderItem(9, item)
        self.tableWidgetListUnemployeds.horizontalHeader().setDefaultSectionSize(91)
        self.label = QtWidgets.QLabel(FormAddNewInterview)
        self.label.setGeometry(QtCore.QRect(20, 10, 941, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(FormAddNewInterview)
        self.label_2.setGeometry(QtCore.QRect(80, 40, 181, 16))
        self.label_2.setObjectName("label_2")
        self.pushButtonCreateInterview = QtWidgets.QPushButton(FormAddNewInterview)
        self.pushButtonCreateInterview.setGeometry(QtCore.QRect(440, 800, 171, 31))
        self.pushButtonCreateInterview.setObjectName("pushButtonCreateInterview")
        self.pushButtonListUnemployeds = QtWidgets.QPushButton(FormAddNewInterview)
        self.pushButtonListUnemployeds.setGeometry(QtCore.QRect(370, 450, 301, 31))
        self.pushButtonListUnemployeds.setObjectName("pushButtonListUnemployeds")
        self.label_3 = QtWidgets.QLabel(FormAddNewInterview)
        self.label_3.setGeometry(QtCore.QRect(260, 370, 101, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(FormAddNewInterview)
        self.label_4.setGeometry(QtCore.QRect(260, 400, 101, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(FormAddNewInterview)
        self.label_5.setGeometry(QtCore.QRect(660, 370, 71, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(FormAddNewInterview)
        self.label_6.setGeometry(QtCore.QRect(660, 400, 101, 31))
        self.label_6.setObjectName("label_6")
        self.widget = QtWidgets.QWidget(FormAddNewInterview)
        self.widget.setGeometry(QtCore.QRect(350, 400, 151, 21))
        self.widget.setObjectName("widget")
        self.radio_evli = QtWidgets.QRadioButton(self.widget)
        self.radio_evli.setGeometry(QtCore.QRect(10, 0, 61, 23))
        self.radio_evli.setObjectName("radio_evli")
        self.radio_bekar = QtWidgets.QRadioButton(self.widget)
        self.radio_bekar.setGeometry(QtCore.QRect(70, 0, 61, 23))
        self.radio_bekar.setObjectName("radio_bekar")
        self.widget_2 = QtWidgets.QWidget(FormAddNewInterview)
        self.widget_2.setGeometry(QtCore.QRect(730, 370, 151, 21))
        self.widget_2.setObjectName("widget_2")
        self.radio_erkek = QtWidgets.QRadioButton(self.widget_2)
        self.radio_erkek.setGeometry(QtCore.QRect(0, 0, 61, 23))
        self.radio_erkek.setObjectName("radio_erkek")
        self.radio_kadin = QtWidgets.QRadioButton(self.widget_2)
        self.radio_kadin.setGeometry(QtCore.QRect(70, 0, 71, 23))
        self.radio_kadin.setObjectName("radio_kadin")
        self.dateEdit = QtWidgets.QDateEdit(FormAddNewInterview)
        self.dateEdit.setGeometry(QtCore.QRect(770, 400, 110, 26))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEditEnd = QtWidgets.QDateEdit(FormAddNewInterview)
        self.dateEditEnd.setGeometry(QtCore.QRect(900, 400, 110, 26))
        self.dateEditEnd.setObjectName("dateEditEnd")
        self.spinBox = QtWidgets.QSpinBox(FormAddNewInterview)
        self.spinBox.setGeometry(QtCore.QRect(350, 370, 51, 21))
        self.spinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.spinBox.setObjectName("spinBox")
        self.label_7 = QtWidgets.QLabel(FormAddNewInterview)
        self.label_7.setGeometry(QtCore.QRect(80, 466, 181, 20))
        self.label_7.setObjectName("label_7")
        self.error_dialog = QtWidgets.QErrorMessage()
        self.retranslateUi(FormAddNewInterview)
        
        QtCore.QMetaObject.connectSlotsByName(FormAddNewInterview)

    def retranslateUi(self, FormAddNewInterview):
        _translate = QtCore.QCoreApplication.translate
        FormAddNewInterview.setWindowTitle(_translate("FormAddNewInterview", "Form"))
        item = self.tableWidgetListFirms.horizontalHeaderItem(0)
        item.setText(_translate("FormAddNewInterview", "Firma ID"))
        item = self.tableWidgetListFirms.horizontalHeaderItem(1)
        item.setText(_translate("FormAddNewInterview", "Firma Adı"))
        item = self.tableWidgetListFirms.horizontalHeaderItem(2)
        item.setText(_translate("FormAddNewInterview", "Firma Adres"))
        item = self.tableWidgetListFirms.horizontalHeaderItem(3)
        item.setText(_translate("FormAddNewInterview", "Firma Telefon"))
        item = self.tableWidgetListFirms.horizontalHeaderItem(4)
        item.setText(_translate("FormAddNewInterview", "Eğitim Gereksinimi"))
        item = self.tableWidgetListFirms.horizontalHeaderItem(5)
        item.setText(_translate("FormAddNewInterview", "Engel İzni"))
        item = self.tableWidgetListFirms.horizontalHeaderItem(6)
        item.setText(_translate("FormAddNewInterview", "Sicil Koşulu"))
        item = self.tableWidgetListUnemployeds.horizontalHeaderItem(0)
        item.setText(_translate("FormAddNewInterview", "Tc No"))
        item = self.tableWidgetListUnemployeds.horizontalHeaderItem(1)
        item.setText(_translate("FormAddNewInterview", "İsim"))
        item = self.tableWidgetListUnemployeds.horizontalHeaderItem(2)
        item.setText(_translate("FormAddNewInterview", "Meslek"))
        item = self.tableWidgetListUnemployeds.horizontalHeaderItem(3)
        item.setText(_translate("FormAddNewInterview", "Tecrübe"))
        item = self.tableWidgetListUnemployeds.horizontalHeaderItem(4)
        item.setText(_translate("FormAddNewInterview", "Eğitim"))
        item = self.tableWidgetListUnemployeds.horizontalHeaderItem(5)
        item.setText(_translate("FormAddNewInterview", "Sicil"))
        item = self.tableWidgetListUnemployeds.horizontalHeaderItem(6)
        item.setText(_translate("FormAddNewInterview", "Engel"))
        item = self.tableWidgetListUnemployeds.horizontalHeaderItem(7)
        item.setText(_translate("FormAddNewInterview", "Medeni Hal"))
        item = self.tableWidgetListUnemployeds.horizontalHeaderItem(8)
        item.setText(_translate("FormAddNewInterview", "Cinsiyet"))
        item = self.tableWidgetListUnemployeds.horizontalHeaderItem(9)
        item.setText(_translate("FormAddNewInterview", "Doğum Tarihi"))
        self.label.setText(_translate("FormAddNewInterview", "Mülakat Oluştur"))
        self.label_2.setText(_translate("FormAddNewInterview", "Firma Seç:"))
        self.pushButtonCreateInterview.setText(_translate("FormAddNewInterview", "Mülakatı Oluştur"))
        self.pushButtonListUnemployeds.setText(_translate("FormAddNewInterview", "Gereksinimlere Uyan Başvuruları Listele"))
        self.label_3.setText(_translate("FormAddNewInterview", "Tecrübe:"))
        self.label_4.setText(_translate("FormAddNewInterview", "Medeni Hal:"))
        self.label_5.setText(_translate("FormAddNewInterview", "Cinsiyet:"))
        self.label_6.setText(_translate("FormAddNewInterview", "Doğum Aralığı:"))
        self.radio_evli.setText(_translate("FormAddNewInterview", "Evli"))
        self.radio_bekar.setText(_translate("FormAddNewInterview", "Bekar"))
        self.radio_erkek.setText(_translate("FormAddNewInterview", "Erkek"))
        self.radio_kadin.setText(_translate("FormAddNewInterview", "Kadın"))
        self.label_7.setText(_translate("FormAddNewInterview", "Uyumlu başvurular:"))
        self.radio_evli.setChecked(True)
        self.radio_erkek.setChecked(True)
        self.tableWidgetListUnemployeds.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetListUnemployeds.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidgetListFirms.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetListFirms.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.listFirms()
        self.pushButtonListUnemployeds.clicked.connect(self.listUnemployeds)
        self.pushButtonCreateInterview.clicked.connect(self.createNewInterview)

    def createNewInterview(self):
        if self.tableWidgetListFirms.selectedIndexes():
            interviews=[]
            for ssn in unemployeds_ssn:
                interviews.append({"worker_ssn":ssn,"firm_id":selectedFirmId})

            message=vtConnection.createNewInterview(interviews)
            self.error_dialog.showMessage(message)
        else:
            self.error_dialog.showMessage('Firma seçip filtre uygulayınız!!!')

    def listFirms(self):
        firms_data = vtConnection.readFirms()
        self.tableWidgetListFirms.clearContents()
        self.tableWidgetListFirms.setRowCount(0)
        i = 0
        for firm_data in firms_data:
            self.tableWidgetListFirms.insertRow(i)
            self.tableWidgetListFirms.setItem(i, 0, QtWidgets.QTableWidgetItem(str(firm_data['id'])))
            self.tableWidgetListFirms.setItem(i, 1, QtWidgets.QTableWidgetItem(firm_data['name_']))
            self.tableWidgetListFirms.setItem(i, 2, QtWidgets.QTableWidgetItem(firm_data['address']))
            self.tableWidgetListFirms.setItem(i, 3, QtWidgets.QTableWidgetItem(firm_data['phone']))
            self.tableWidgetListFirms.setItem(i, 4, QtWidgets.QTableWidgetItem(firm_data['req_grad_level']))
            self.tableWidgetListFirms.setItem(i, 5, QtWidgets.QTableWidgetItem(str(firm_data['disable_permission'])))
            if firm_data['registery_permission']:
                self.tableWidgetListFirms.setItem(i, 6, QtWidgets.QTableWidgetItem('Serbest'))
            else:
                self.tableWidgetListFirms.setItem(i, 6, QtWidgets.QTableWidgetItem('Katı'))
            i = i + 1
        self.tableWidgetListFirms.sortItems(0, QtCore.Qt.DescendingOrder)

    def listUnemployeds(self):
        
        if self.tableWidgetListFirms.selectedIndexes():
            global selectedFirmId
            selectedFirmId=int(self.tableWidgetListFirms.selectedIndexes()[0].data())
            unemployeds_data = vtConnection.listUnemployedsByRequirementsOfFirm(selectedFirmId,
                                                                                self.radio_evli.isChecked(),
                                                                                self.radio_erkek.isChecked(),
                                                                                self.spinBox.value(),
                                                                                self.dateEdit.date().toString('dd/MM/yyyy'),
                                                                                self.dateEditEnd.date().toString('dd/MM/yyyy'))
            self.tableWidgetListUnemployeds.clearContents()
            self.tableWidgetListUnemployeds.setRowCount(0)
            if len(unemployeds_data)==0:
                self.error_dialog.showMessage("Bu filtreye uygun başvuru bulunmamaktadır.")
            else:
                i = 0
                global unemployeds_ssn
                unemployeds_ssn=[]
                for unemployed_data in unemployeds_data:
                    unemployeds_ssn.append(unemployed_data['ssn'])
                    self.tableWidgetListUnemployeds.insertRow(i)
                    self.tableWidgetListUnemployeds.setItem(i, 0, QtWidgets.QTableWidgetItem(str(unemployed_data['ssn'])))
                    self.tableWidgetListUnemployeds.setItem(i, 1, QtWidgets.QTableWidgetItem(unemployed_data['name_']))
                    self.tableWidgetListUnemployeds.setItem(i, 2, QtWidgets.QTableWidgetItem(unemployed_data['job']))
                    self.tableWidgetListUnemployeds.setItem(i, 3, QtWidgets.QTableWidgetItem(str(unemployed_data['experience'])))
                    self.tableWidgetListUnemployeds.setItem(i, 4, QtWidgets.QTableWidgetItem(unemployed_data['grad_level']))
                    if unemployed_data['registery']:
                        self.tableWidgetListUnemployeds.setItem(i, 5, QtWidgets.QTableWidgetItem('Temiz'))
                    else:
                        self.tableWidgetListUnemployeds.setItem(i, 5, QtWidgets.QTableWidgetItem('Temiz Değil'))
                    self.tableWidgetListUnemployeds.setItem(i, 6, QtWidgets.QTableWidgetItem(str(unemployed_data['disable_level'])))
                    if unemployed_data['marriage']:
                        self.tableWidgetListUnemployeds.setItem(i, 7, QtWidgets.QTableWidgetItem('Evli'))
                    else:
                        self.tableWidgetListUnemployeds.setItem(i, 7, QtWidgets.QTableWidgetItem('Bekar'))
                    if unemployed_data['gender']:
                        self.tableWidgetListUnemployeds.setItem(i, 8, QtWidgets.QTableWidgetItem('Erkek'))
                    else:
                        self.tableWidgetListUnemployeds.setItem(i, 8, QtWidgets.QTableWidgetItem('Kadın'))
                    self.tableWidgetListUnemployeds.setItem(i, 9, QtWidgets.QTableWidgetItem(str(unemployed_data['birthdate'])[0:10]))
                    i = i + 1    
        else:
            self.error_dialog.showMessage("Seçili 1 firma olmalıdır!!!")
 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormAddNewInterview = QtWidgets.QWidget()
    ui = Ui_FormAddNewInterview()
    ui.setupUi(FormAddNewInterview)
    FormAddNewInterview.show()
    sys.exit(app.exec_())
